### PR TITLE
(Feature) Protofire link

### PR DESCRIPTION
**Pull request by gabitoesmiapodo**
Added a `protofire.io` link. Not the best thing in the world, but it works.

I don't think there's a "nice" or pleasant way to add Protofire's logo too (not with the current layout, at least).

**Screenshot:**

Screen Shot 2020-10-26 at 16 53 56

### CODE REVIEW

**Comment by mgarciap** [comment]
Is it too ugly to replicate exactly what we have now at the left of the search bar (Filecoin logo + Filecoin + CID Checker) but with Protofire (Protofire Logo + 'Built by Protofire') at the right of the bar?

image

**Comment by gabitoesmiapodo** [comment]
@mgarciap You could end up with something like this. It'll also impact on the responsive / mobile versions.

I'll leave the _"Is it too ugly"_ considerations up to you.

asdfg

**Comment by mgarciap** [comment]
LGTM

**Comment by gabitoesmiapodo** [comment]
It should look like this now:

Screen Shot 2020-10-28 at 16 25 20

**Pull request merged**
